In [107]:
from pathlib import Path
import json

import pandas as pd
import sys

PROJECT_ROOT = Path.cwd().parent
RAW_DATA = PROJECT_ROOT / "data" / "raw"

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.data_loader import (
    load_matches,
    load_events,
    load_lineups,
    load_360,
)

print(PROJECT_ROOT)
print(RAW_DATA)

c:\Users\usasl\SoccerDataAnalysisProjects\bayer-leverkusen-2324-analysis
c:\Users\usasl\SoccerDataAnalysisProjects\bayer-leverkusen-2324-analysis\data\raw

In [2]:
matches_path = RAW_DATA / "matches" / "9" / "281.json"

with open(matches_path, "r", encoding="utf-8") as file:
    matches = json.load(file)

In [8]:
type(matches)
len(matches)
type(matches[0])
matches[0].keys()

dict_keys(['match_id', 'match_date', 'kick_off', 'competition', 'season', 'home_team', 'away_team', 'home_score', 'away_score', 'match_status', 'match_status_360', 'last_updated', 'last_updated_360', 'metadata', 'match_week', 'competition_stage', 'stadium', 'referee'])

In [9]:
matches[0]

{'match_id': 3895292,
 'match_date': '2024-04-06',
 'kick_off': '15:30:00.000',
 'competition': {'competition_id': 9,
  'country_name': 'Germany',
  'competition_name': '1. Bundesliga'},
 'season': {'season_id': 281, 'season_name': '2023/2024'},
 'home_team': {'home_team_id': 190,
  'home_team_name': 'Union Berlin',
  'home_team_gender': 'male',
  'home_team_group': None,
  'country': {'id': 85, 'name': 'Germany'},
  'managers': [{'id': 176,
    'name': 'Nenad Bjelica',
    'nickname': None,
    'dob': '1971-08-20',
    'country': {'id': 56, 'name': 'Croatia'}}]},
 'away_team': {'away_team_id': 904,
  'away_team_name': 'Bayer Leverkusen',
  'away_team_gender': 'male',
  'away_team_group': None,
  'country': {'id': 85, 'name': 'Germany'},
  'managers': [{'id': 1000310,
    'name': 'Xabier Alonso Olano',
    'nickname': 'Xabi Alonso',
    'dob': '1981-11-25',
    'country': {'id': 214, 'name': 'Spain'}}]},
 'home_score': 0,
 'away_score': 1,
 'match_status': 'available',
 'match_status_360': 'available',
 'last_updated': '2024-07-31T11:03:01.588127',
 'last_updated_360': '2025-07-06T04:26:07.636270',
 'metadata': {'data_version': '1.1.0',
  'shot_fidelity_version': '2',
  'xy_fidelity_version': '2'},
 'match_week': 28,
 'competition_stage': {'id': 1, 'name': 'Regular Season'},
 'stadium': {'id': 560,
  'name': 'Stadion An der Alten Försterei',
  'country': {'id': 85, 'name': 'Germany'}},
 'referee': {'id': 235,
  'name': 'Benjamin Brand',
  'country': {'id': 85, 'name': 'Germany'}}}

In [10]:
print(matches[0]["home_team"])
print(matches[0]["away_team"])
print(matches[0]["competition"])
print(matches[0]["season"])

{'home_team_id': 190, 'home_team_name': 'Union Berlin', 'home_team_gender': 'male', 'home_team_group': None, 'country': {'id': 85, 'name': 'Germany'}, 'managers': [{'id': 176, 'name': 'Nenad Bjelica', 'nickname': None, 'dob': '1971-08-20', 'country': {'id': 56, 'name': 'Croatia'}}]}
{'away_team_id': 904, 'away_team_name': 'Bayer Leverkusen', 'away_team_gender': 'male', 'away_team_group': None, 'country': {'id': 85, 'name': 'Germany'}, 'managers': [{'id': 1000310, 'name': 'Xabier Alonso Olano', 'nickname': 'Xabi Alonso', 'dob': '1981-11-25', 'country': {'id': 214, 'name': 'Spain'}}]}
{'competition_id': 9, 'country_name': 'Germany', 'competition_name': '1. Bundesliga'}
{'season_id': 281, 'season_name': '2023/2024'}

In [11]:
print(matches[0]["home_team"]["home_team_name"])
print(matches[0]["away_team"]["away_team_name"])

Union Berlin
Bayer Leverkusen

In [12]:
matches_df = pd.DataFrame(matches)

In [13]:
matches_df.head()

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,metadata,match_week,competition_stage,stadium,referee
0,3895292,2024-04-06,15:30:00.000,"{'competition_id': 9, 'country_name': 'Germany...","{'season_id': 281, 'season_name': '2023/2024'}","{'home_team_id': 190, 'home_team_name': 'Union...","{'away_team_id': 904, 'away_team_name': 'Bayer...",0,1,available,available,2024-07-31T11:03:01.588127,2025-07-06T04:26:07.636270,"{'data_version': '1.1.0', 'shot_fidelity_versi...",28,"{'id': 1, 'name': 'Regular Season'}","{'id': 560, 'name': 'Stadion An der Alten Förs...","{'id': 235, 'name': 'Benjamin Brand', 'country..."
1,3895320,2024-04-27,19:30:00.000,"{'competition_id': 9, 'country_name': 'Germany...","{'season_id': 281, 'season_name': '2023/2024'}","{'home_team_id': 904, 'home_team_name': 'Bayer...","{'away_team_id': 174, 'away_team_name': 'VfB S...",2,2,available,available,2024-08-06T15:42:54.389576,2025-01-02T11:05:23.462823,"{'data_version': '1.1.0', 'shot_fidelity_versi...",31,"{'id': 1, 'name': 'Regular Season'}","{'id': 377, 'name': 'BayArena', 'country': {'i...","{'id': 241, 'name': 'Felix Zwayer', 'country':..."
2,3895158,2023-12-03,18:30:00.000,"{'competition_id': 9, 'country_name': 'Germany...","{'season_id': 281, 'season_name': '2023/2024'}","{'home_team_id': 904, 'home_team_name': 'Bayer...","{'away_team_id': 180, 'away_team_name': 'Borus...",1,1,available,available,2024-07-29T12:45:28.152104,2025-09-07T09:35:11.061799,"{'data_version': '1.1.0', 'shot_fidelity_versi...",13,"{'id': 1, 'name': 'Regular Season'}","{'id': 377, 'name': 'BayArena', 'country': {'i...","{'id': 225, 'name': 'Daniel Siebert', 'country..."
3,3895107,2023-10-08,16:30:00.000,"{'competition_id': 9, 'country_name': 'Germany...","{'season_id': 281, 'season_name': '2023/2024'}","{'home_team_id': 904, 'home_team_name': 'Bayer...","{'away_team_id': 186, 'away_team_name': 'FC Kö...",3,0,available,available,2024-07-29T12:43:40.606973,2024-10-14T10:35:11.461679,"{'data_version': '1.1.0', 'shot_fidelity_versi...",7,"{'id': 1, 'name': 'Regular Season'}","{'id': 377, 'name': 'BayArena', 'country': {'i...","{'id': 241, 'name': 'Felix Zwayer', 'country':..."
4,3895340,2024-05-12,20:30:00.000,"{'competition_id': 9, 'country_name': 'Germany...","{'season_id': 281, 'season_name': '2023/2024'}","{'home_team_id': 868, 'home_team_name': 'Bochu...","{'away_team_id': 904, 'away_team_name': 'Bayer...",0,5,available,available,2024-07-29T12:16:45.557236,2025-01-01T12:14:22.212709,"{'data_version': '1.1.0', 'shot_fidelity_versi...",33,"{'id': 1, 'name': 'Regular Season'}","{'id': 550, 'name': 'Vonovia Ruhrstadion', 'co...","{'id': 235, 'name': 'Benjamin Brand', 'country..."

In [ ]:
matches_df.shape

(34, 18)

In [16]:
matches_df.columns

Index(['match_id', 'match_date', 'kick_off', 'competition', 'season',
       'home_team', 'away_team', 'home_score', 'away_score', 'match_status',
       'match_status_360', 'last_updated', 'last_updated_360', 'metadata',
       'match_week', 'competition_stage', 'stadium', 'referee'],
      dtype='str')

In [17]:
type(matches[0]["home_team"])

dict

In [18]:
match_summary_df = pd.DataFrame(
    {
        "match_id": [match["match_id"] for match in matches],
        "match_date": [match["match_date"] for match in matches],
        "match_week": [match["match_week"] for match in matches],
        "home_team": [match["home_team"]["home_team_name"] for match in matches],
        "away_team": [match["away_team"]["away_team_name"] for match in matches],
        "home_score": [match["home_score"] for match in matches],
        "away_score": [match["away_score"] for match in matches],
    }
)

In [20]:
match_summary_df.head()

,match_id,match_date,match_week,home_team,away_team,home_score,away_score
0,3895292,2024-04-06,28,Union Berlin,Bayer Leverkusen,0,1
1,3895320,2024-04-27,31,Bayer Leverkusen,VfB Stuttgart,2,2
2,3895158,2023-12-03,13,Bayer Leverkusen,Borussia Dortmund,1,1
3,3895107,2023-10-08,7,Bayer Leverkusen,FC Köln,3,0
4,3895340,2024-05-12,33,Bochum,Bayer Leverkusen,0,5

In [21]:
match_summary_df.dtypes

match_id      int64
match_date      str
match_week    int64
home_team       str
away_team       str
home_score    int64
away_score    int64
dtype: object

In [22]:
match_summary_df["match_date"] = pd.to_datetime(
    match_summary_df["match_date"]
)

In [24]:
match_summary_df.dtypes

match_id               int64
match_date    datetime64[us]
match_week             int64
home_team                str
away_team                str
home_score             int64
away_score             int64
dtype: object

In [25]:
match_summary_df.head()

,match_id,match_date,match_week,home_team,away_team,home_score,away_score
0,3895292,2024-04-06,28,Union Berlin,Bayer Leverkusen,0,1
1,3895320,2024-04-27,31,Bayer Leverkusen,VfB Stuttgart,2,2
2,3895158,2023-12-03,13,Bayer Leverkusen,Borussia Dortmund,1,1
3,3895107,2023-10-08,7,Bayer Leverkusen,FC Köln,3,0
4,3895340,2024-05-12,33,Bochum,Bayer Leverkusen,0,5

In [26]:
match_summary_df.sort_values("match_date").head()

,match_id,match_date,match_week,home_team,away_team,home_score,away_score
33,3895052,2023-08-19,1,Bayer Leverkusen,RB Leipzig,3,2
32,3895060,2023-08-26,2,Borussia Mönchengladbach,Bayer Leverkusen,0,3
31,3895067,2023-09-02,3,Bayer Leverkusen,Darmstadt 98,5,1
16,3895074,2023-09-15,4,Bayern Munich,Bayer Leverkusen,2,2
18,3895086,2023-09-24,5,Bayer Leverkusen,FC Heidenheim,4,1

In [27]:
match_summary_df.isna().sum()

match_id      0
match_date    0
match_week    0
home_team     0
away_team     0
home_score    0
away_score    0
dtype: int64

In [28]:
match_summary_df.duplicated().sum()

np.int64(0)

In [29]:
match_summary_df["match_id"].nunique()

34

In [30]:
def get_leverkusen_result(row):
    if row["home_team"] == "Bayer Leverkusen":
        leverkusen_score = row["home_score"]
        opponent_score = row["away_score"]
    else:
        leverkusen_score = row["away_score"]
        opponent_score = row["home_score"]

    if leverkusen_score > opponent_score:
        return "Win"
    elif leverkusen_score < opponent_score:
        return "Loss"
    else:
        return "Draw"

In [32]:
match_summary_df["result"] = match_summary_df.apply(
    get_leverkusen_result,
    axis=1
)

In [35]:
match_summary_df[
    ["match_date", "home_team", "away_team", "home_score", "away_score", "result"]
].sort_values("match_date").head(10)

,match_date,home_team,away_team,home_score,away_score,result
33,2023-08-19,Bayer Leverkusen,RB Leipzig,3,2,Win
32,2023-08-26,Borussia Mönchengladbach,Bayer Leverkusen,0,3,Win
31,2023-09-02,Bayer Leverkusen,Darmstadt 98,5,1,Win
16,2023-09-15,Bayern Munich,Bayer Leverkusen,2,2,Draw
18,2023-09-24,Bayer Leverkusen,FC Heidenheim,4,1,Win
30,2023-09-30,FSV Mainz 05,Bayer Leverkusen,0,3,Win
3,2023-10-08,Bayer Leverkusen,FC Köln,3,0,Win
29,2023-10-21,Wolfsburg,Bayer Leverkusen,1,2,Win
15,2023-10-29,Bayer Leverkusen,Freiburg,2,1,Win
14,2023-11-04,Hoffenheim,Bayer Leverkusen,2,3,Win

In [36]:
match_summary_df["result"].value_counts()

result
Win     28
Draw     6
Name: count, dtype: int64

In [37]:
match_summary_df["opponent"] = match_summary_df.apply(
    lambda row: (
        row["away_team"]
        if row["home_team"] == "Bayer Leverkusen"
        else row["home_team"]
    ),
    axis=1,
)

In [38]:
match_summary_df["venue"] = match_summary_df["home_team"].apply(
    lambda team: "Home" if team == "Bayer Leverkusen" else "Away"
)

In [39]:
match_summary_df["goals_for"] = match_summary_df.apply(
    lambda row: (
        row["home_score"]
        if row["home_team"] == "Bayer Leverkusen"
        else row["away_score"]
    ),
    axis=1,
)

match_summary_df["goals_against"] = match_summary_df.apply(
    lambda row: (
        row["away_score"]
        if row["home_team"] == "Bayer Leverkusen"
        else row["home_score"]
    ),
    axis=1,
)

In [40]:
match_summary_df["goal_difference"] = (
    match_summary_df["goals_for"]
    - match_summary_df["goals_against"]
)

In [41]:
match_summary_df[
    [
        "match_week",
        "match_date",
        "opponent",
        "venue",
        "goals_for",
        "goals_against",
        "goal_difference",
        "result",
    ]
].sort_values("match_date").head(10)

,match_week,match_date,opponent,venue,goals_for,goals_against,goal_difference,result
33,1,2023-08-19,RB Leipzig,Home,3,2,1,Win
32,2,2023-08-26,Borussia Mönchengladbach,Away,3,0,3,Win
31,3,2023-09-02,Darmstadt 98,Home,5,1,4,Win
16,4,2023-09-15,Bayern Munich,Away,2,2,0,Draw
18,5,2023-09-24,FC Heidenheim,Home,4,1,3,Win
30,6,2023-09-30,FSV Mainz 05,Away,3,0,3,Win
3,7,2023-10-08,FC Köln,Home,3,0,3,Win
29,8,2023-10-21,Wolfsburg,Away,2,1,1,Win
15,9,2023-10-29,Freiburg,Home,2,1,1,Win
14,10,2023-11-04,Hoffenheim,Away,3,2,1,Win

In [42]:
match_summary_df["goals_for"].sum()

np.int64(89)

In [43]:
match_summary_df["goals_against"].sum()

np.int64(24)

In [44]:
match_summary_df["goal_difference"].sum()

np.int64(65)

In [45]:
match_summary_df["venue"].value_counts()

venue
Away    17
Home    17
Name: count, dtype: int64

In [46]:
first_match = (
    match_summary_df
    .sort_values("match_date")
    .iloc[0]
)

first_match

match_id                       3895052
match_date         2023-08-19 00:00:00
match_week                           1
home_team             Bayer Leverkusen
away_team                   RB Leipzig
home_score                           3
away_score                           2
result                             Win
opponent                    RB Leipzig
venue                             Home
goals_for                            3
goals_against                        2
goal_difference                      1
Name: 33, dtype: object

In [47]:
first_match_id = first_match["match_id"]

print(first_match_id)
print(first_match["match_date"])
print(first_match["opponent"])
print(first_match["venue"])

3895052
2023-08-19 00:00:00
RB Leipzig
Home

In [48]:
event_path = RAW_DATA / "events" / f"{first_match_id}.json"

print(event_path)

c:\Users\usasl\SoccerDataAnalysisProjects\bayer-leverkusen-2324-analysis\data\raw\events\3895052.json

In [49]:
with open(event_path, "r", encoding="utf-8") as file:
    events = json.load(file)

In [50]:
print(type(events))
print(len(events))
print(type(events[0]))
print(events[0].keys())

<class 'list'>
3739
<class 'dict'>
dict_keys(['id', 'index', 'period', 'timestamp', 'minute', 'second', 'type', 'possession', 'possession_team', 'play_pattern', 'team', 'duration', 'tactics'])

In [51]:
events_df = pd.DataFrame(events)

In [52]:
events_df.head()

,id,index,period,timestamp,minute,second,type,possession,possession_team,play_pattern,...,duel,clearance,dribble,foul_won,ball_recovery,injury_stoppage,foul_committed,substitution,bad_behaviour,50_50
0,69bb4fa7-f177-49a8-9b19-7c01cd9d9a9c,1,1,00:00:00.000,0,0,"{'id': 35, 'name': 'Starting XI'}",1,"{'id': 904, 'name': 'Bayer Leverkusen'}","{'id': 1, 'name': 'Regular Play'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,9790a466-9c56-42aa-96aa-a9ad1a6f8811,2,1,00:00:00.000,0,0,"{'id': 35, 'name': 'Starting XI'}",1,"{'id': 904, 'name': 'Bayer Leverkusen'}","{'id': 1, 'name': 'Regular Play'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,c6762724-3ad0-4ed1-b232-7f32ac192ec6,3,1,00:00:00.000,0,0,"{'id': 18, 'name': 'Half Start'}",1,"{'id': 904, 'name': 'Bayer Leverkusen'}","{'id': 1, 'name': 'Regular Play'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ba22283a-c920-448c-804e-3737cccd9fff,4,1,00:00:00.000,0,0,"{'id': 18, 'name': 'Half Start'}",1,"{'id': 904, 'name': 'Bayer Leverkusen'}","{'id': 1, 'name': 'Regular Play'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,9a50295b-7f7a-449c-9ef3-87e60467e8e1,5,1,00:00:00.773,0,0,"{'id': 30, 'name': 'Pass'}",2,"{'id': 182, 'name': 'RB Leipzig'}","{'id': 9, 'name': 'From Kick Off'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
events_df.shape

(3739, 37)

In [55]:
events_df.columns

Index(['id', 'index', 'period', 'timestamp', 'minute', 'second', 'type',
       'possession', 'possession_team', 'play_pattern', 'team', 'duration',
       'tactics', 'related_events', 'off_camera', 'player', 'position',
       'location', 'pass', 'carry', 'ball_receipt', 'out', 'under_pressure',
       'interception', 'shot', 'goalkeeper', 'counterpress', 'duel',
       'clearance', 'dribble', 'foul_won', 'ball_recovery', 'injury_stoppage',
       'foul_committed', 'substitution', 'bad_behaviour', '50_50'],
      dtype='str')

In [62]:
print(len(events))
print(events[0].keys())

3739
dict_keys(['id', 'index', 'period', 'timestamp', 'minute', 'second', 'type', 'possession', 'possession_team', 'play_pattern', 'team', 'duration', 'tactics'])

In [82]:
events[0]["type"]

{'id': 35, 'name': 'Starting XI'}

In [85]:
event_types = [
    event["type"]["name"] 
    for event in events
]

In [86]:
pd.Series(event_types).value_counts()

Pass                 1081
Ball Receipt*        1019
Carry                 892
Pressure              297
Ball Recovery          87
Duel                   53
Goal Keeper            33
Block                  32
Foul Committed         26
Clearance              26
Dribble                26
Foul Won               25
Shot                   25
Interception           24
Miscontrol             20
Dispossessed           19
Dribbled Past          12
Substitution            9
Injury Stoppage         8
Half Start              4
Referee Ball-Drop       4
Half End                4
Shield                  3
Tactical Shift          3
Starting XI             2
50/50                   2
Bad Behaviour           1
Player Off              1
Player On               1
Name: count, dtype: int64

In [87]:
pass_event = next(
    event
    for event in events
    if event["type"]["name"] == "Pass"
)

In [88]:
pass_event.keys()

dict_keys(['id', 'index', 'period', 'timestamp', 'minute', 'second', 'type', 'possession', 'possession_team', 'play_pattern', 'off_camera', 'team', 'player', 'position', 'location', 'duration', 'related_events', 'pass'])

In [89]:
pass_event

{'id': '9a50295b-7f7a-449c-9ef3-87e60467e8e1',
 'index': 5,
 'period': 1,
 'timestamp': '00:00:00.773',
 'minute': 0,
 'second': 0,
 'type': {'id': 30, 'name': 'Pass'},
 'possession': 2,
 'possession_team': {'id': 182, 'name': 'RB Leipzig'},
 'play_pattern': {'id': 9, 'name': 'From Kick Off'},
 'off_camera': True,
 'team': {'id': 182, 'name': 'RB Leipzig'},
 'player': {'id': 16275, 'name': 'Ikoma Loïs Openda'},
 'position': {'id': 22, 'name': 'Right Center Forward'},
 'location': [61.0, 40.1],
 'duration': 0.321221,
 'related_events': ['17c0df03-219a-4603-befe-8cd2f58d6d47'],
 'pass': {'recipient': {'id': 16532, 'name': 'Daniel Olmo Carvajal'},
  'length': 4.060788,
  'angle': 2.968347,
  'height': {'id': 1, 'name': 'Ground Pass'},
  'end_location': [57.0, 40.8],
  'body_part': {'id': 40, 'name': 'Right Foot'},
  'type': {'id': 65, 'name': 'Kick Off'}}}

In [91]:
pass_event["pass"].keys()

dict_keys(['recipient', 'length', 'angle', 'height', 'end_location', 'body_part', 'type'])

In [92]:
passes = [
    event
    for event in events
    if event["type"]["name"] == "Pass"
]

In [93]:
len(passes)

1081

In [94]:
passes_with_outcome = [
    event
    for event in passes
    if "outcome" in event["pass"]
]

len(passes_with_outcome)

173

In [95]:
pd.Series(
    [
        event["pass"]["outcome"]["name"]
        for event in passes_with_outcome
    ]
).value_counts()

Incomplete          144
Out                  20
Unknown               5
Pass Offside          2
Injury Clearance      2
Name: count, dtype: int64

In [96]:
leverkusen_events = [
    event
    for event in events
    if event["team"]["name"] == "Bayer Leverkusen"
]

In [97]:
len(leverkusen_events)

1662

In [98]:
leverkusen_event_types = [
    event["type"]["name"]
    for event in leverkusen_events
]

pd.Series(leverkusen_event_types).value_counts()

Pass                 481
Ball Receipt*        460
Carry                374
Pressure             122
Ball Recovery         42
Duel                  27
Block                 18
Goal Keeper           17
Clearance             15
Foul Committed        14
Dribble               12
Foul Won              12
Interception          11
Shot                  11
Dispossessed          11
Miscontrol             7
Dribbled Past          5
Injury Stoppage        4
Substitution           4
Shield                 3
Half Start             2
Referee Ball-Drop      2
Half End               2
Starting XI            1
Bad Behaviour          1
Tactical Shift         1
Player Off             1
Player On              1
50/50                  1
Name: count, dtype: int64

In [99]:
shot_event = next(
    event
    for event in events
    if event["type"]["name"] == "Shot"
)

In [100]:
print(shot_event.keys())
print(shot_event["shot"].keys())

dict_keys(['id', 'index', 'period', 'timestamp', 'minute', 'second', 'type', 'possession', 'possession_team', 'play_pattern', 'team', 'player', 'position', 'location', 'duration', 'related_events', 'shot'])
dict_keys(['statsbomb_xg', 'end_location', 'type', 'outcome', 'technique', 'body_part', 'freeze_frame'])

In [101]:
shot_event["shot"]

{'statsbomb_xg': 0.020733545,
 'end_location': [117.4, 40.3, 2.0],
 'type': {'id': 87, 'name': 'Open Play'},
 'outcome': {'id': 100, 'name': 'Saved'},
 'technique': {'id': 93, 'name': 'Normal'},
 'body_part': {'id': 38, 'name': 'Left Foot'},
 'freeze_frame': [{'location': [118.4, 39.1],
   'player': {'id': 15155, 'name': 'Janis Blaswich'},
   'position': {'id': 1, 'name': 'Goalkeeper'},
   'teammate': False},
  {'location': [99.8, 47.4],
   'player': {'id': 32289, 'name': 'Victor Okoh Boniface'},
   'position': {'id': 23, 'name': 'Center Forward'},
   'teammate': True},
  {'location': [100.6, 34.2],
   'player': {'id': 40724, 'name': 'Florian Wirtz'},
   'position': {'id': 21, 'name': 'Left Wing'},
   'teammate': True},
  {'location': [86.3, 63.3],
   'player': {'id': 32712, 'name': 'Jeremie Frimpong'},
   'position': {'id': 7, 'name': 'Right Wing Back'},
   'teammate': True},
  {'location': [95.7, 21.1],
   'player': {'id': 10336, 'name': 'Alejandro Grimaldo García'},
   'position': {'id': 8, 'name': 'Left Wing Back'},
   'teammate': True},
  {'location': [87.3, 40.4],
   'player': {'id': 28268, 'name': 'Exequiel Alejandro Palacios'},
   'position': {'id': 9, 'name': 'Right Defensive Midfield'},
   'teammate': True},
  {'location': [73.6, 31.5],
   'player': {'id': 30606, 'name': 'Edmond Fayçal Tapsoba'},
   'position': {'id': 5, 'name': 'Left Center Back'},
   'teammate': True},
  {'location': [70.5, 58.1],
   'player': {'id': 27133, 'name': 'Odilon Kossonou'},
   'position': {'id': 3, 'name': 'Right Center Back'},
   'teammate': True},
  {'location': [103.4, 47.9],
   'player': {'id': 12034, 'name': 'David Raum'},
   'position': {'id': 6, 'name': 'Left Back'},
   'teammate': False},
  {'location': [105.6, 41.4],
   'player': {'id': 8509, 'name': 'Willi Orban'},
   'position': {'id': 5, 'name': 'Left Center Back'},
   'teammate': False},
  {'location': [98.0, 44.3],
   'player': {'id': 8769, 'name': 'Xaver Schlager'},
   'position': {'id': 11, 'name': 'Left Defensive Midfield'},
   'teammate': False},
  {'location': [102.0, 32.4],
   'player': {'id': 30360, 'name': 'Mohamed Simakan'},
   'position': {'id': 3, 'name': 'Right Center Back'},
   'teammate': False},
  {'location': [98.8, 35.6],
   'player': {'id': 39460, 'name': 'Nicolas Seiwald'},
   'position': {'id': 9, 'name': 'Right Defensive Midfield'},
   'teammate': False},
  {'location': [92.4, 45.3],
   'player': {'id': 16532, 'name': 'Daniel Olmo Carvajal'},
   'position': {'id': 24, 'name': 'Left Center Forward'},
   'teammate': False},
  {'location': [98.3, 26.4],
   'player': {'id': 8211, 'name': 'Benjamin Henrichs'},
   'position': {'id': 2, 'name': 'Right Back'},
   'teammate': False},
  {'location': [94.0, 29.5],
   'player': {'id': 39167, 'name': 'Xavi Simons'},
   'position': {'id': 12, 'name': 'Right Midfield'},
   'teammate': False},
  {'location': [80.2, 30.1],
   'player': {'id': 16275, 'name': 'Ikoma Loïs Openda'},
   'position': {'id': 22, 'name': 'Right Center Forward'},
   'teammate': False},
  {'location': [73.0, 56.3],
   'player': {'id': 5557, 'name': 'Timo Werner'},
   'position': {'id': 16, 'name': 'Left Midfield'},
   'teammate': False},
  {'location': [102.4, 46.8],
   'player': {'id': 8804, 'name': 'Jonas Hofmann'},
   'position': {'id': 17, 'name': 'Right Wing'},
   'teammate': True}]}

In [102]:
from src.data_loader import load_matches

ModuleNotFoundError: No module named 'src'

In [108]:
loaded_matches = load_matches()

len(loaded_matches)

34

In [111]:
loaded_events = load_events(first_match_id)

len(loaded_events)

3739

In [112]:
events == loaded_events

True